### ISSUE TITLE
Tool can not be used

### ISSUE THREAD

**Issue by laitianwen** [griptape-ai/ComfyUI-Griptape#104]
ERROR ToolkitTask 83bbd926ead04c61b7ce15e53c931ad8
Error code: 400 - {'type': 'error', 'error':
{'type': 'invalid_request_error', 'message':
'tools.0.name: Field required'}}
Traceback (most recent call last):

**Comment by shhlife** [comment]
Hi,
Sorry you are hitting the error - can you tell me more about what your node setup looks like? That will help me debug it :) 

Cheers!
-jason

**Comment by laitianwen** [comment]
江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "griptape-ai/ComfyUI-Griptape"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月12日(星期一) 凌晨2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [griptape-ai/ComfyUI-Griptape] Tool can not be used (Issue #104)





 
Hi,
 Sorry you are hitting the error - can you tell me more about what your node setup looks like? That will help me debug it :)
 
Cheers!
 -jason

**Comment by laitianwen** [comment]
------------------ Original ------------------
From: Jason Schleifer ***@***.***&gt;
Date: Mon,Aug 12,2024 2:06 AM
To: griptape-ai/ComfyUI-Griptape ***@***.***&gt;
Cc: laitianwen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [griptape-ai/ComfyUI-Griptape] Tool can not be used (Issue #104)





 
Hi,
 Sorry you are hitting the error - can you tell me more about what your node setup looks like? That will help me debug it :)
 
Cheers!
 -jason

**Comment by laitianwen** [comment]
ok,I'll give you a screenshot
![0812_1](https://github.com/user-attachments/assets/dabf8b4f-be74-4721-8539-dd5c7efb9cee)

**Comment by shhlife** [comment]
Thanks for this!

If I understand your flow correctly, you'll like to have one agent be able to call another agent that can create graphic design images, right?

There are a couple of ways to go about this - and a pretty clear addition I need to accomplish with our ComfyUI nodes in order to do exactly what you want. 

First, it looks like you're wanting to use Claude to act as your main agent model. To do this, I'd recommend using the `Griptape Agent Config: Anthropic` node. It will set the model correctly.

![image](https://github.com/user-attachments/assets/a57797a5-c293-4b58-8704-1afeb738f353)

Second, in your OpenAI Compatible node, you're using your API key as the `api_key_env_var`. This is meant to point to an environment variable, not the api key itself because security-wise you shouldn't be including actual api keys in your workflow. In fact, I'd recommend deleting and re-creating your current key since you posted it in the image. The recommended workflow would be to save your key in your `.env` file in your base comfyUI directory. This is mentioned in the README for our nodes: 
https://github.com/griptape-ai/ComfyUI-Griptape?tab=readme-ov-file#installation

Third - it looks like to achieve exactly what you want, I need to create a Tool for image generation, which you would give the agent with the image generation skills, and then figure out how to get the output to be displayed properly. I'll work on that.

In the meantime, here's a node flow that I think will get you what you would like:
![image](https://github.com/user-attachments/assets/c76a38c4-d4a7-426e-9e17-f452bce9e5f7)

**Comment by laitianwen** [comment]
you misunderstood, I just want to use the role tool to generate prompts, not images











&nbsp;


江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason ***@***.***&gt;; 
发送时间: 2024年8月13日(星期二) 凌晨0:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [griptape-ai/ComfyUI-Griptape] Tool can not be used (Issue #104)














 
&nbsp;谢谢你！
 

如果我正确理解您的流程，您会希望一个代理能够调用另一个可以创建图形设计图像的代理，对吧？
 

有几种方法可以解决这个问题 - 我需要使用 ComfyUI 节点完成一个非常明确的补充，以便准确地完成您想要的操作。
 

首先，看起来你想用克劳德作为你的主要代理模型。为此，我建议使用Griptape Agent Config: Anthropic节点。它将正确设置模型。
 
&nbsp;image.png（在网络上查看）
 

其次，在 OpenAI Compatible 节点中，您使用 API 密钥作为api_key_env_var 。这意味着指向一个环境变量，而不是 api 密钥本身，因为从安全角度来看，您不应该在工作流程中包含实际的 api 密钥。事实上，我建议删除并重新创建当前密钥，因为您将其发布在图像中。建议的工作流程是将密钥保存在 comfyUI 基本目录中的.env文件中。我们的节点的自述文件中提到了这一点：
 https://github.com/griptape-ai/ComfyUI-Griptape?tab=readme-ov-file#installation
 

第三 - 看起来要达到您想要的效果，我需要创建一个图像生成工具，您可以为代理提供图像生成技能，然后弄清楚如何使输出正确显示。我会努力解决这个问题。
 

与此同时，我认为这是一个节点流程，可以满足您的需求：
 &nbsp;image.png（在网络上查看）
 
—

直接回复此电子邮件、在 GitHub 上查看或取消订阅。

您收到此消息是因为您创作了该主题。  Message ID: ***@***.***&gt;

**Comment by shhlife** [comment]
Ah! Okay, cool! When was the last time you updated the griptape nodes?

**Comment by laitianwen** [comment]
Yesterday morning, it could not be used after the update.



------------------ Original ------------------
From: Jason Schleifer ***@***.***&gt;
Date: Tue,Aug 13,2024 0:56 AM
To: griptape-ai/ComfyUI-Griptape ***@***.***&gt;
Cc: laitianwen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [griptape-ai/ComfyUI-Griptape] Tool can not be used (Issue #104)

**Comment by shhlife** [comment]
Okay - I’m out at meetings today but will take a look tonight.

**Comment by laitianwen** [comment]
Okay, thank you very much！！！



------------------ Original ------------------
From: Jason Schleifer ***@***.***&gt;
Date: Tue,Aug 13,2024 1:47 AM
To: griptape-ai/ComfyUI-Griptape ***@***.***&gt;
Cc: laitianwen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [griptape-ai/ComfyUI-Griptape] Tool can not be used (Issue #104)

**Comment by shhlife** [comment]
Sorry, coming back to this. Just to confirm - you'd like to be able to have the agent create a prompt for an image generation, not actually generate the image itself, correct?

**Comment by laitianwen** [comment]
Now there is no problem, it can be used.



------------------ Original ------------------
From: Jason Schleifer ***@***.***&gt;
Date: Thu,Sep 5,2024 9:10 AM
To: griptape-ai/ComfyUI-Griptape ***@***.***&gt;
Cc: laitianwen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [griptape-ai/ComfyUI-Griptape] Tool can not be used (Issue #104)





 
Sorry, coming back to this. Just to confirm - you'd like to be able to have the agent create a prompt for an image generation, not actually generate the image itself, correct?

**Comment by shhlife** [comment]
awesome, thanks!
